default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gohub_development
  username: *********
  password: *********
  host: localhost
  port: 5432


test:
  <<: *default
  database: gohub_test
  username: *********
  password: *********
  host: localhost
  port: 5432

production:
  <<: *default
  database: gohub_production
  username: *********
  password: <%= ENV['GOHUB_DATABASE_PASSWORD'] %>
